//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "agency")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub agency_id: String,
    pub agency_name: Option<String>,
    pub agency_url: Option<String>,
    pub agency_timezone: Option<String>,
    pub agency_lang: Option<String>,
    pub agency_phone: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::route::Entity")]
    Route,
}

impl Related<super::route::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Route.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
