//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "calendar")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub service_id: String,
    pub monday: bool,
    pub tuesday: bool,
    pub wednesday: bool,
    pub thursday: bool,
    pub friday: bool,
    pub saturday: bool,
    pub sunday: bool,
    pub start_date: Date,
    pub end_date: Date,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::calendardate::Entity")]
    Calendardate,
    #[sea_orm(has_many = "super::trip::Entity")]
    Trip,
}

impl Related<super::calendardate::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Calendardate.def()
    }
}

impl Related<super::trip::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trip.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
