//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "calendardate")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub service_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub date: Date,
    pub exception_type: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::calendar::Entity",
        from = "Column::ServiceId",
        to = "super::calendar::Column::ServiceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Calendar,
}

impl Related<super::calendar::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Calendar.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
