//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "frequency")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub trip_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub start_time: String,
    pub end_time: Option<String>,
    pub headway_secs: i32,
    pub exact_times: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::trip::Entity",
        from = "Column::TripId",
        to = "super::trip::Column::TripId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Trip,
}

impl Related<super::trip::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trip.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
