//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "level")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub level_id: String,
    pub level_index: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::stop::Entity")]
    Stop,
}

impl Related<super::stop::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stop.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
