//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod agency;
pub mod calendar;
pub mod calendardate;
pub mod frequency;
pub mod level;
pub mod pathway;
pub mod route;
pub mod stop;
pub mod stoptime;
pub mod trip;
