//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pathway")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub pathway_id: String,
    pub from_stop_id: Option<String>,
    pub to_stop_id: Option<String>,
    pub pathway_mode: Option<i32>,
    pub is_bidirectional: Option<bool>,
    pub traversal_time: Option<i32>,
    pub length: Option<Decimal>,
    pub stair_count: Option<i32>,
    pub max_slope: Option<Decimal>,
    pub min_width: Option<Decimal>,
    pub signposted_as: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::stop::Entity",
        from = "Column::FromStopId",
        to = "super::stop::Column::StopId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Stop2,
    #[sea_orm(
        belongs_to = "super::stop::Entity",
        from = "Column::ToStopId",
        to = "super::stop::Column::StopId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Stop1,
}

impl ActiveModelBehavior for ActiveModel {}
