//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "route")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub route_id: String,
    pub agency_id: Option<String>,
    pub route_short_name: Option<String>,
    pub route_long_name: Option<String>,
    pub route_type: Option<i32>,
    pub route_color: Option<String>,
    pub route_text_color: Option<String>,
    pub route_desc: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::agency::Entity",
        from = "Column::AgencyId",
        to = "super::agency::Column::AgencyId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Agency,
    #[sea_orm(has_many = "super::trip::Entity")]
    Trip,
}

impl Related<super::agency::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Agency.def()
    }
}

impl Related<super::trip::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trip.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
