//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "stoptime")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub trip_id: String,
    pub stop_id: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub stop_sequence: i32,
    pub pickup_type: Option<i32>,
    pub drop_off_type: Option<i32>,
    pub stop_headsign: Option<String>,
    pub arrival_time: Option<i32>,
    pub departure_time: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::stop::Entity",
        from = "Column::StopId",
        to = "super::stop::Column::StopId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Stop,
    #[sea_orm(
        belongs_to = "super::trip::Entity",
        from = "Column::TripId",
        to = "super::trip::Column::TripId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Trip,
}

impl Related<super::stop::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stop.def()
    }
}

impl Related<super::trip::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trip.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
