//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "stop")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub stop_id: String,
    pub stop_code: Option<String>,
    pub stop_name: Option<String>,
    pub stop_desc: Option<String>,
    pub stop_lat: Option<Decimal>,
    pub stop_lon: Option<Decimal>,
    pub location_type: Option<i32>,
    pub parent_station: Option<String>,
    pub wheelchair_boarding: Option<i32>,
    pub platform_code: Option<String>,
    pub level_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::level::Entity",
        from = "Column::LevelId",
        to = "super::level::Column::LevelId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Level,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentStation",
        to = "Column::StopId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::stoptime::Entity")]
    Stoptime,
}

impl Related<super::level::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Level.def()
    }
}

impl Related<super::stoptime::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stoptime.def()
    }
}

impl Related<super::trip::Entity> for Entity {
    fn to() -> RelationDef {
        super::stoptime::Relation::Trip.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::stoptime::Relation::Stop.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
