//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "trip")]
pub struct Model {
    pub route_id: Option<String>,
    pub service_id: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub trip_id: String,
    pub trip_headsign: Option<String>,
    pub trip_short_name: Option<String>,
    pub direction_id: Option<i32>,
    pub block_id: Option<String>,
    pub wheelchair_accessible: Option<i32>,
    pub bikes_allowed: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::calendar::Entity",
        from = "Column::ServiceId",
        to = "super::calendar::Column::ServiceId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Calendar,
    #[sea_orm(has_many = "super::frequency::Entity")]
    Frequency,
    #[sea_orm(
        belongs_to = "super::route::Entity",
        from = "Column::RouteId",
        to = "super::route::Column::RouteId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Route,
    #[sea_orm(has_many = "super::stoptime::Entity")]
    Stoptime,
}

impl Related<super::calendar::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Calendar.def()
    }
}

impl Related<super::frequency::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Frequency.def()
    }
}

impl Related<super::route::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Route.def()
    }
}

impl Related<super::stoptime::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stoptime.def()
    }
}

impl Related<super::stop::Entity> for Entity {
    fn to() -> RelationDef {
        super::stoptime::Relation::Stop.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::stoptime::Relation::Trip.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
