name: Run Chaos Monkey

on:
  schedule:
    # Trigger the workflow every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allows running manually

jobs:
  chaos:
    runs-on: ubuntu-latest
    environment: main
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        GH_ENVIRONMENT_TOKEN: ${{ secrets.GH_ENVIRONMENT_TOKEN }}
        GITHUB_ENVIRONMENT_NAME: main
        
    steps:
      - name: Run Chaos Monkey Script
        run: |
          pg-chaos-monkey
